# Use the standard Nginx image from Container Registry
...

# copy the nginx.conf to /etc/nginx/nginx.conf
...

# expose port 8080
...

# Start Nginx when the container has provisioned.
CMD ["nginx", "-g", "daemon off;"]