---
version: '3'
services:
  my-first-hello-world:
    build:
      context: ./folder
      dockerfile: Dockerfile
    image: java-image

  my-second-hello-world:
    build:
      context: ./folder
      dockerfile: Dockerfile
    image: java-image